### ISSUE TITLE
Upstream license may have changed to GPLv3?

### ISSUE THREAD

**Issue by y4r9** [fiji-BIG/StackReg#2]
Not to open the license can of worms again, but from what I can tell the upstream license is now GPLv3 for most of these projects (see "IX. Conditions of Use" at [https://bigwww.epfl.ch/thevenaz/stackreg/](https://bigwww.epfl.ch/thevenaz/stackreg/) and the GPLv3 label behind the project name at [https://bigwww.epfl.ch/algorithms.html](https://bigwww.epfl.ch/algorithms.html)). Would this enable contributing to this project under a GPLv3 license?
Also, my thanks to those having asked for permission to distribute StackReg and related projects with fiji  and also to those who granted the permission.

**Comment by ctrueden** [comment]
@y4r9 Yes, the license did change last year, which is great. It has been on my list to update the BIG project licenses accordingly here (https://github.com/ctrueden/tasks/issues/19), but I've just been too busy.

**Comment by y4r9** [comment]
@ctrueden thank you for your quick response! That answers my question. Please don’t feel urged to prioritize this in any way.
